package nginx

type DefaultAccessLog struct {
	// Requester's IP address.
	RemoteAddr string
	// Reserved field, fixed value is "-".
	Reserved string
	// User from basicauth
	RemoteUser string
	// Time when received the request.
	TimeLocal string
	// Request including query string.
	Request string
	// HTTP status code returned.
	Status string
	// Upstream traffic generated by the request.
	BodySentBytes string
	// HTTP referer header.
	Referer string
	// HTTP User-Agent header.
	UserAgent string
	// HTTP x-forwarded-for header.
	ForwardedFor string
}
